### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by c-martinez** [fair-software/badge#10]
In the long run, it would be good if we have a pip-installable command line tool which runs all check scripts and produces a badge (url for the badge).

**Comment by c-martinez** [comment]
Example run:
```
$ how-fair-is https://github.com/fair-software/badge-test
https://img.shields.io/badge/fair--software.eu-%E2%98%86%E2%98%85%E2%98%85%E2%98%86%E2%98%86-orange
```

**Comment by jspaaks** [comment]
done in https://github.com/fair-software/badge/tree/a40dbd03aba35cdb282d3c7c894f81fe90ae3048, closing.
