### ISSUE TITLE
List of registries

### ISSUE THREAD

**Issue by c-martinez** [fair-software/badge#6]
Registries listed  https://github.com/NLeSC/awesome-research-software-registries need to be (magically) available in a machine readable format.

**Comment by mkuzak** [comment]
After discussing with @c-martinez 
we will need a list with pairs:
name_of_the_registries : pattern_of_registry (based on the button)

**Comment by c-martinez** [comment]
Initial list is ready, but it will continue to grow in the future.

closing issue.
